import { Analytics } from '@vercel/analytics/react';
import { SpeedInsights } from '@vercel/speed-insights/next';
import Script from 'next/script';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Joelma Lima ADV",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Script id="leadster-chatbot" strategy="beforeInteractive">
          {`
            (function(a,b,c,d){
              try {
                var e = b.head || b.getElementsByTagName("head")[0];
                var f = b.createElement("script");
                f.setAttribute("src", c);
                f.setAttribute("charset", "UTF-8");
                f.defer = true;
                a.neuroleadId = d;
                e.appendChild(f);
              } catch (g) {}
            })(window, document, "https://cdn.leadster.com.br/neurolead/neurolead.min.js", "sylKvctMZst73z3CtcVObgz5l");
          `}
        </Script>
        <Script id="facebook-pixel" strategy="beforeInteractive">
          {`
            !function(f,b,e,v,n,t,s)
            {if(f.fbq)return;n=f.fbq=function(){n.callMethod?
            n.callMethod.apply(n,arguments):n.queue.push(arguments)};
            if(!f._fbq)f._fbq=n;n.push=n;n.loaded=!0;n.version='2.0';
            n.queue=[];t=b.createElement(e);t.async=!0;
            t.src=v;s=b.getElementsByTagName(e)[0];
            s.parentNode.insertBefore(t,s)}(window, document,'script',
            'https://connect.facebook.net/en_US/fbevents.js');
            fbq('init', '890868959894660');
            fbq('track', 'PageView');
          `}
        </Script>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
